version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: safeuser
      POSTGRES_PASSWORD: safepassword
      POSTGRES_DB: safedb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: safeuser
      DB_PASSWORD: safepassword
      DB_NAME: safedb
      JWT_SECRET: ini_secret_key_ganti_nanti
      PORT: "8080"

volumes:
  pg_data: