// Generated file containing all country codes, ISO codes, and flag emojis
class Country {
  final String nameEn;
  final String nameId;
  final String code;
  final String dialCode;
  final String flag;

  const Country({
    required this.nameEn,
    required this.nameId,
    required this.code,
    required this.dialCode,
    required this.flag,
  });
}

class CountryCodes {
  static String getFlagEmoji(String countryCode) {
    final codePoints = countryCode
        .toUpperCase()
        .split('')
        .map((char) => 127397 + char.codeUnitAt(0));
    return String.fromCharCodes(codePoints);
  }

  static final List<Country> countries = const [
    Country(
      nameEn: 'Afghanistan',
      nameId: 'Afghanistan',
      code: 'AF',
      dialCode: '+93',
      flag: '🇦🇫',
    ),
    Country(
      nameEn: 'Aland Islands',
      nameId: 'Aland Islands',
      code: 'AX',
      dialCode: '+358',
      flag: '🇦🇽',
    ),
    Country(
      nameEn: 'Albania',
      nameId: 'Albania',
      code: 'AL',
      dialCode: '+355',
      flag: '🇦🇱',
    ),
    Country(
      nameEn: 'Algeria',
      nameId: 'Algeria',
      code: 'DZ',
      dialCode: '+213',
      flag: '🇩🇿',
    ),
    Country(
      nameEn: 'AmericanSamoa',
      nameId: 'AmericanSamoa',
      code: 'AS',
      dialCode: '+1684',
      flag: '🇦🇸',
    ),
    Country(
      nameEn: 'Andorra',
      nameId: 'Andorra',
      code: 'AD',
      dialCode: '+376',
      flag: '🇦🇩',
    ),
    Country(
      nameEn: 'Angola',
      nameId: 'Angola',
      code: 'AO',
      dialCode: '+244',
      flag: '🇦🇴',
    ),
    Country(
      nameEn: 'Anguilla',
      nameId: 'Anguilla',
      code: 'AI',
      dialCode: '+1264',
      flag: '🇦🇮',
    ),
    Country(
      nameEn: 'Antarctica',
      nameId: 'Antarctica',
      code: 'AQ',
      dialCode: '+672',
      flag: '🇦🇶',
    ),
    Country(
      nameEn: 'Antigua and Barbuda',
      nameId: 'Antigua and Barbuda',
      code: 'AG',
      dialCode: '+1268',
      flag: '🇦🇬',
    ),
    Country(
      nameEn: 'Argentina',
      nameId: 'Argentina',
      code: 'AR',
      dialCode: '+54',
      flag: '🇦🇷',
    ),
    Country(
      nameEn: 'Armenia',
      nameId: 'Armenia',
      code: 'AM',
      dialCode: '+374',
      flag: '🇦🇲',
    ),
    Country(
      nameEn: 'Aruba',
      nameId: 'Aruba',
      code: 'AW',
      dialCode: '+297',
      flag: '🇦🇼',
    ),
    Country(
      nameEn: 'Australia',
      nameId: 'Australia',
      code: 'AU',
      dialCode: '+61',
      flag: '🇦🇺',
    ),
    Country(
      nameEn: 'Austria',
      nameId: 'Austria',
      code: 'AT',
      dialCode: '+43',
      flag: '🇦🇹',
    ),
    Country(
      nameEn: 'Azerbaijan',
      nameId: 'Azerbaijan',
      code: 'AZ',
      dialCode: '+994',
      flag: '🇦🇿',
    ),
    Country(
      nameEn: 'Bahamas',
      nameId: 'Bahamas',
      code: 'BS',
      dialCode: '+1242',
      flag: '🇧🇸',
    ),
    Country(
      nameEn: 'Bahrain',
      nameId: 'Bahrain',
      code: 'BH',
      dialCode: '+973',
      flag: '🇧🇭',
    ),
    Country(
      nameEn: 'Bangladesh',
      nameId: 'Bangladesh',
      code: 'BD',
      dialCode: '+880',
      flag: '🇧🇩',
    ),
    Country(
      nameEn: 'Barbados',
      nameId: 'Barbados',
      code: 'BB',
      dialCode: '+1246',
      flag: '🇧🇧',
    ),
    Country(
      nameEn: 'Belarus',
      nameId: 'Belarus',
      code: 'BY',
      dialCode: '+375',
      flag: '🇧🇾',
    ),
    Country(
      nameEn: 'Belgium',
      nameId: 'Belgia',
      code: 'BE',
      dialCode: '+32',
      flag: '🇧🇪',
    ),
    Country(
      nameEn: 'Belize',
      nameId: 'Belize',
      code: 'BZ',
      dialCode: '+501',
      flag: '🇧🇿',
    ),
    Country(
      nameEn: 'Benin',
      nameId: 'Benin',
      code: 'BJ',
      dialCode: '+229',
      flag: '🇧🇯',
    ),
    Country(
      nameEn: 'Bermuda',
      nameId: 'Bermuda',
      code: 'BM',
      dialCode: '+1441',
      flag: '🇧🇲',
    ),
    Country(
      nameEn: 'Bhutan',
      nameId: 'Bhutan',
      code: 'BT',
      dialCode: '+975',
      flag: '🇧🇹',
    ),
    Country(
      nameEn: 'Bolivia, Plurinational State of',
      nameId: 'Bolivia, Plurinational State of',
      code: 'BO',
      dialCode: '+591',
      flag: '🇧🇴',
    ),
    Country(
      nameEn: 'Bosnia and Herzegovina',
      nameId: 'Bosnia and Herzegovina',
      code: 'BA',
      dialCode: '+387',
      flag: '🇧🇦',
    ),
    Country(
      nameEn: 'Botswana',
      nameId: 'Botswana',
      code: 'BW',
      dialCode: '+267',
      flag: '🇧🇼',
    ),
    Country(
      nameEn: 'Brazil',
      nameId: 'Brasil',
      code: 'BR',
      dialCode: '+55',
      flag: '🇧🇷',
    ),
    Country(
      nameEn: 'British Indian Ocean Territory',
      nameId: 'British Indian Ocean Territory',
      code: 'IO',
      dialCode: '+246',
      flag: '🇮🇴',
    ),
    Country(
      nameEn: 'Brunei Darussalam',
      nameId: 'Brunei Darussalam',
      code: 'BN',
      dialCode: '+673',
      flag: '🇧🇳',
    ),
    Country(
      nameEn: 'Bulgaria',
      nameId: 'Bulgaria',
      code: 'BG',
      dialCode: '+359',
      flag: '🇧🇬',
    ),
    Country(
      nameEn: 'Burkina Faso',
      nameId: 'Burkina Faso',
      code: 'BF',
      dialCode: '+226',
      flag: '🇧🇫',
    ),
    Country(
      nameEn: 'Burundi',
      nameId: 'Burundi',
      code: 'BI',
      dialCode: '+257',
      flag: '🇧🇮',
    ),
    Country(
      nameEn: 'Cambodia',
      nameId: 'Cambodia',
      code: 'KH',
      dialCode: '+855',
      flag: '🇰🇭',
    ),
    Country(
      nameEn: 'Cameroon',
      nameId: 'Cameroon',
      code: 'CM',
      dialCode: '+237',
      flag: '🇨🇲',
    ),
    Country(
      nameEn: 'Canada',
      nameId: 'Canada',
      code: 'CA',
      dialCode: '+1',
      flag: '🇨🇦',
    ),
    Country(
      nameEn: 'Cape Verde',
      nameId: 'Cape Verde',
      code: 'CV',
      dialCode: '+238',
      flag: '🇨🇻',
    ),
    Country(
      nameEn: 'Cayman Islands',
      nameId: 'Cayman Islands',
      code: 'KY',
      dialCode: '+ 345',
      flag: '🇰🇾',
    ),
    Country(
      nameEn: 'Central African Republic',
      nameId: 'Central African Republic',
      code: 'CF',
      dialCode: '+236',
      flag: '🇨🇫',
    ),
    Country(
      nameEn: 'Chad',
      nameId: 'Chad',
      code: 'TD',
      dialCode: '+235',
      flag: '🇹🇩',
    ),
    Country(
      nameEn: 'Chile',
      nameId: 'Chile',
      code: 'CL',
      dialCode: '+56',
      flag: '🇨🇱',
    ),
    Country(
      nameEn: 'China',
      nameId: 'Tiongkok',
      code: 'CN',
      dialCode: '+86',
      flag: '🇨🇳',
    ),
    Country(
      nameEn: 'Christmas Island',
      nameId: 'Christmas Island',
      code: 'CX',
      dialCode: '+61',
      flag: '🇨🇽',
    ),
    Country(
      nameEn: 'Cocos (Keeling) Islands',
      nameId: 'Cocos (Keeling) Islands',
      code: 'CC',
      dialCode: '+61',
      flag: '🇨🇨',
    ),
    Country(
      nameEn: 'Colombia',
      nameId: 'Colombia',
      code: 'CO',
      dialCode: '+57',
      flag: '🇨🇴',
    ),
    Country(
      nameEn: 'Comoros',
      nameId: 'Comoros',
      code: 'KM',
      dialCode: '+269',
      flag: '🇰🇲',
    ),
    Country(
      nameEn: 'Congo',
      nameId: 'Congo',
      code: 'CG',
      dialCode: '+242',
      flag: '🇨🇬',
    ),
    Country(
      nameEn: 'Congo, The Democratic Republic of the Congo',
      nameId: 'Congo, The Democratic Republic of the Congo',
      code: 'CD',
      dialCode: '+243',
      flag: '🇨🇩',
    ),
    Country(
      nameEn: 'Cook Islands',
      nameId: 'Cook Islands',
      code: 'CK',
      dialCode: '+682',
      flag: '🇨🇰',
    ),
    Country(
      nameEn: 'Costa Rica',
      nameId: 'Costa Rica',
      code: 'CR',
      dialCode: '+506',
      flag: '🇨🇷',
    ),
    Country(
      nameEn: 'Cote d\'Ivoire',
      nameId: 'Cote d\'Ivoire',
      code: 'CI',
      dialCode: '+225',
      flag: '🇨🇮',
    ),
    Country(
      nameEn: 'Croatia',
      nameId: 'Croatia',
      code: 'HR',
      dialCode: '+385',
      flag: '🇭🇷',
    ),
    Country(
      nameEn: 'Cuba',
      nameId: 'Cuba',
      code: 'CU',
      dialCode: '+53',
      flag: '🇨🇺',
    ),
    Country(
      nameEn: 'Cyprus',
      nameId: 'Cyprus',
      code: 'CY',
      dialCode: '+357',
      flag: '🇨🇾',
    ),
    Country(
      nameEn: 'Czech Republic',
      nameId: 'Czech Republic',
      code: 'CZ',
      dialCode: '+420',
      flag: '🇨🇿',
    ),
    Country(
      nameEn: 'Denmark',
      nameId: 'Denmark',
      code: 'DK',
      dialCode: '+45',
      flag: '🇩🇰',
    ),
    Country(
      nameEn: 'Djibouti',
      nameId: 'Djibouti',
      code: 'DJ',
      dialCode: '+253',
      flag: '🇩🇯',
    ),
    Country(
      nameEn: 'Dominica',
      nameId: 'Dominica',
      code: 'DM',
      dialCode: '+1767',
      flag: '🇩🇲',
    ),
    Country(
      nameEn: 'Dominican Republic',
      nameId: 'Dominican Republic',
      code: 'DO',
      dialCode: '+1849',
      flag: '🇩🇴',
    ),
    Country(
      nameEn: 'Ecuador',
      nameId: 'Ecuador',
      code: 'EC',
      dialCode: '+593',
      flag: '🇪🇨',
    ),
    Country(
      nameEn: 'Egypt',
      nameId: 'Mesir',
      code: 'EG',
      dialCode: '+20',
      flag: '🇪🇬',
    ),
    Country(
      nameEn: 'El Salvador',
      nameId: 'El Salvador',
      code: 'SV',
      dialCode: '+503',
      flag: '🇸🇻',
    ),
    Country(
      nameEn: 'Equatorial Guinea',
      nameId: 'Equatorial Guinea',
      code: 'GQ',
      dialCode: '+240',
      flag: '🇬🇶',
    ),
    Country(
      nameEn: 'Eritrea',
      nameId: 'Eritrea',
      code: 'ER',
      dialCode: '+291',
      flag: '🇪🇷',
    ),
    Country(
      nameEn: 'Estonia',
      nameId: 'Estonia',
      code: 'EE',
      dialCode: '+372',
      flag: '🇪🇪',
    ),
    Country(
      nameEn: 'Ethiopia',
      nameId: 'Ethiopia',
      code: 'ET',
      dialCode: '+251',
      flag: '🇪🇹',
    ),
    Country(
      nameEn: 'Falkland Islands (Malvinas)',
      nameId: 'Falkland Islands (Malvinas)',
      code: 'FK',
      dialCode: '+500',
      flag: '🇫🇰',
    ),
    Country(
      nameEn: 'Faroe Islands',
      nameId: 'Faroe Islands',
      code: 'FO',
      dialCode: '+298',
      flag: '🇫🇴',
    ),
    Country(
      nameEn: 'Fiji',
      nameId: 'Fiji',
      code: 'FJ',
      dialCode: '+679',
      flag: '🇫🇯',
    ),
    Country(
      nameEn: 'Finland',
      nameId: 'Finland',
      code: 'FI',
      dialCode: '+358',
      flag: '🇫🇮',
    ),
    Country(
      nameEn: 'France',
      nameId: 'Prancis',
      code: 'FR',
      dialCode: '+33',
      flag: '🇫🇷',
    ),
    Country(
      nameEn: 'French Guiana',
      nameId: 'French Guiana',
      code: 'GF',
      dialCode: '+594',
      flag: '🇬🇫',
    ),
    Country(
      nameEn: 'French Polynesia',
      nameId: 'French Polynesia',
      code: 'PF',
      dialCode: '+689',
      flag: '🇵🇫',
    ),
    Country(
      nameEn: 'Gabon',
      nameId: 'Gabon',
      code: 'GA',
      dialCode: '+241',
      flag: '🇬🇦',
    ),
    Country(
      nameEn: 'Gambia',
      nameId: 'Gambia',
      code: 'GM',
      dialCode: '+220',
      flag: '🇬🇲',
    ),
    Country(
      nameEn: 'Georgia',
      nameId: 'Georgia',
      code: 'GE',
      dialCode: '+995',
      flag: '🇬🇪',
    ),
    Country(
      nameEn: 'Germany',
      nameId: 'Jerman',
      code: 'DE',
      dialCode: '+49',
      flag: '🇩🇪',
    ),
    Country(
      nameEn: 'Ghana',
      nameId: 'Ghana',
      code: 'GH',
      dialCode: '+233',
      flag: '🇬🇭',
    ),
    Country(
      nameEn: 'Gibraltar',
      nameId: 'Gibraltar',
      code: 'GI',
      dialCode: '+350',
      flag: '🇬🇮',
    ),
    Country(
      nameEn: 'Greece',
      nameId: 'Yunani',
      code: 'GR',
      dialCode: '+30',
      flag: '🇬🇷',
    ),
    Country(
      nameEn: 'Greenland',
      nameId: 'Greenland',
      code: 'GL',
      dialCode: '+299',
      flag: '🇬🇱',
    ),
    Country(
      nameEn: 'Grenada',
      nameId: 'Grenada',
      code: 'GD',
      dialCode: '+1473',
      flag: '🇬🇩',
    ),
    Country(
      nameEn: 'Guadeloupe',
      nameId: 'Guadeloupe',
      code: 'GP',
      dialCode: '+590',
      flag: '🇬🇵',
    ),
    Country(
      nameEn: 'Guam',
      nameId: 'Guam',
      code: 'GU',
      dialCode: '+1671',
      flag: '🇬🇺',
    ),
    Country(
      nameEn: 'Guatemala',
      nameId: 'Guatemala',
      code: 'GT',
      dialCode: '+502',
      flag: '🇬🇹',
    ),
    Country(
      nameEn: 'Guernsey',
      nameId: 'Guernsey',
      code: 'GG',
      dialCode: '+44',
      flag: '🇬🇬',
    ),
    Country(
      nameEn: 'Guinea',
      nameId: 'Guinea',
      code: 'GN',
      dialCode: '+224',
      flag: '🇬🇳',
    ),
    Country(
      nameEn: 'Guinea-Bissau',
      nameId: 'Guinea-Bissau',
      code: 'GW',
      dialCode: '+245',
      flag: '🇬🇼',
    ),
    Country(
      nameEn: 'Guyana',
      nameId: 'Guyana',
      code: 'GY',
      dialCode: '+595',
      flag: '🇬🇾',
    ),
    Country(
      nameEn: 'Haiti',
      nameId: 'Haiti',
      code: 'HT',
      dialCode: '+509',
      flag: '🇭🇹',
    ),
    Country(
      nameEn: 'Holy See (Vatican City State)',
      nameId: 'Holy See (Vatican City State)',
      code: 'VA',
      dialCode: '+379',
      flag: '🇻🇦',
    ),
    Country(
      nameEn: 'Honduras',
      nameId: 'Honduras',
      code: 'HN',
      dialCode: '+504',
      flag: '🇭🇳',
    ),
    Country(
      nameEn: 'Hong Kong',
      nameId: 'Hong Kong',
      code: 'HK',
      dialCode: '+852',
      flag: '🇭🇰',
    ),
    Country(
      nameEn: 'Hungary',
      nameId: 'Hungary',
      code: 'HU',
      dialCode: '+36',
      flag: '🇭🇺',
    ),
    Country(
      nameEn: 'Iceland',
      nameId: 'Iceland',
      code: 'IS',
      dialCode: '+354',
      flag: '🇮🇸',
    ),
    Country(
      nameEn: 'India',
      nameId: 'India',
      code: 'IN',
      dialCode: '+91',
      flag: '🇮🇳',
    ),
    Country(
      nameEn: 'Indonesia',
      nameId: 'Indonesia',
      code: 'ID',
      dialCode: '+62',
      flag: '🇮🇩',
    ),
    Country(
      nameEn: 'Iran, Islamic Republic of Persian Gulf',
      nameId: 'Iran, Islamic Republic of Persian Gulf',
      code: 'IR',
      dialCode: '+98',
      flag: '🇮🇷',
    ),
    Country(
      nameEn: 'Iraq',
      nameId: 'Iraq',
      code: 'IQ',
      dialCode: '+964',
      flag: '🇮🇶',
    ),
    Country(
      nameEn: 'Ireland',
      nameId: 'Ireland',
      code: 'IE',
      dialCode: '+353',
      flag: '🇮🇪',
    ),
    Country(
      nameEn: 'Isle of Man',
      nameId: 'Isle of Man',
      code: 'IM',
      dialCode: '+44',
      flag: '🇮🇲',
    ),
    Country(
      nameEn: 'Italy',
      nameId: 'Italia',
      code: 'IT',
      dialCode: '+39',
      flag: '🇮🇹',
    ),
    Country(
      nameEn: 'Jamaica',
      nameId: 'Jamaica',
      code: 'JM',
      dialCode: '+1876',
      flag: '🇯🇲',
    ),
    Country(
      nameEn: 'Japan',
      nameId: 'Jepang',
      code: 'JP',
      dialCode: '+81',
      flag: '🇯🇵',
    ),
    Country(
      nameEn: 'Jersey',
      nameId: 'Jersey',
      code: 'JE',
      dialCode: '+44',
      flag: '🇯🇪',
    ),
    Country(
      nameEn: 'Jordan',
      nameId: 'Jordan',
      code: 'JO',
      dialCode: '+962',
      flag: '🇯🇴',
    ),
    Country(
      nameEn: 'Kazakhstan',
      nameId: 'Kazakhstan',
      code: 'KZ',
      dialCode: '+77',
      flag: '🇰🇿',
    ),
    Country(
      nameEn: 'Kenya',
      nameId: 'Kenya',
      code: 'KE',
      dialCode: '+254',
      flag: '🇰🇪',
    ),
    Country(
      nameEn: 'Kiribati',
      nameId: 'Kiribati',
      code: 'KI',
      dialCode: '+686',
      flag: '🇰🇮',
    ),
    Country(
      nameEn: 'Korea, Democratic People\'s Republic of Korea',
      nameId: 'Korea Utara',
      code: 'KP',
      dialCode: '+850',
      flag: '🇰🇵',
    ),
    Country(
      nameEn: 'Korea, Republic of South Korea',
      nameId: 'Korea Selatan',
      code: 'KR',
      dialCode: '+82',
      flag: '🇰🇷',
    ),
    Country(
      nameEn: 'Kuwait',
      nameId: 'Kuwait',
      code: 'KW',
      dialCode: '+965',
      flag: '🇰🇼',
    ),
    Country(
      nameEn: 'Kyrgyzstan',
      nameId: 'Kyrgyzstan',
      code: 'KG',
      dialCode: '+996',
      flag: '🇰🇬',
    ),
    Country(
      nameEn: 'Laos',
      nameId: 'Laos',
      code: 'LA',
      dialCode: '+856',
      flag: '🇱🇦',
    ),
    Country(
      nameEn: 'Latvia',
      nameId: 'Latvia',
      code: 'LV',
      dialCode: '+371',
      flag: '🇱🇻',
    ),
    Country(
      nameEn: 'Lebanon',
      nameId: 'Lebanon',
      code: 'LB',
      dialCode: '+961',
      flag: '🇱🇧',
    ),
    Country(
      nameEn: 'Lesotho',
      nameId: 'Lesotho',
      code: 'LS',
      dialCode: '+266',
      flag: '🇱🇸',
    ),
    Country(
      nameEn: 'Liberia',
      nameId: 'Liberia',
      code: 'LR',
      dialCode: '+231',
      flag: '🇱🇷',
    ),
    Country(
      nameEn: 'Libyan Arab Jamahiriya',
      nameId: 'Libyan Arab Jamahiriya',
      code: 'LY',
      dialCode: '+218',
      flag: '🇱🇾',
    ),
    Country(
      nameEn: 'Liechtenstein',
      nameId: 'Liechtenstein',
      code: 'LI',
      dialCode: '+423',
      flag: '🇱🇮',
    ),
    Country(
      nameEn: 'Lithuania',
      nameId: 'Lithuania',
      code: 'LT',
      dialCode: '+370',
      flag: '🇱🇹',
    ),
    Country(
      nameEn: 'Luxembourg',
      nameId: 'Luxembourg',
      code: 'LU',
      dialCode: '+352',
      flag: '🇱🇺',
    ),
    Country(
      nameEn: 'Macao',
      nameId: 'Macao',
      code: 'MO',
      dialCode: '+853',
      flag: '🇲🇴',
    ),
    Country(
      nameEn: 'Macedonia',
      nameId: 'Macedonia',
      code: 'MK',
      dialCode: '+389',
      flag: '🇲🇰',
    ),
    Country(
      nameEn: 'Madagascar',
      nameId: 'Madagascar',
      code: 'MG',
      dialCode: '+261',
      flag: '🇲🇬',
    ),
    Country(
      nameEn: 'Malawi',
      nameId: 'Malawi',
      code: 'MW',
      dialCode: '+265',
      flag: '🇲🇼',
    ),
    Country(
      nameEn: 'Malaysia',
      nameId: 'Malaysia',
      code: 'MY',
      dialCode: '+60',
      flag: '🇲🇾',
    ),
    Country(
      nameEn: 'Maldives',
      nameId: 'Maldives',
      code: 'MV',
      dialCode: '+960',
      flag: '🇲🇻',
    ),
    Country(
      nameEn: 'Mali',
      nameId: 'Mali',
      code: 'ML',
      dialCode: '+223',
      flag: '🇲🇱',
    ),
    Country(
      nameEn: 'Malta',
      nameId: 'Malta',
      code: 'MT',
      dialCode: '+356',
      flag: '🇲🇹',
    ),
    Country(
      nameEn: 'Marshall Islands',
      nameId: 'Marshall Islands',
      code: 'MH',
      dialCode: '+692',
      flag: '🇲🇭',
    ),
    Country(
      nameEn: 'Martinique',
      nameId: 'Martinique',
      code: 'MQ',
      dialCode: '+596',
      flag: '🇲🇶',
    ),
    Country(
      nameEn: 'Mauritania',
      nameId: 'Mauritania',
      code: 'MR',
      dialCode: '+222',
      flag: '🇲🇷',
    ),
    Country(
      nameEn: 'Mauritius',
      nameId: 'Mauritius',
      code: 'MU',
      dialCode: '+230',
      flag: '🇲🇺',
    ),
    Country(
      nameEn: 'Mayotte',
      nameId: 'Mayotte',
      code: 'YT',
      dialCode: '+262',
      flag: '🇾🇹',
    ),
    Country(
      nameEn: 'Mexico',
      nameId: 'Mexico',
      code: 'MX',
      dialCode: '+52',
      flag: '🇲🇽',
    ),
    Country(
      nameEn: 'Micronesia, Federated States of Micronesia',
      nameId: 'Micronesia, Federated States of Micronesia',
      code: 'FM',
      dialCode: '+691',
      flag: '🇫🇲',
    ),
    Country(
      nameEn: 'Moldova',
      nameId: 'Moldova',
      code: 'MD',
      dialCode: '+373',
      flag: '🇲🇩',
    ),
    Country(
      nameEn: 'Monaco',
      nameId: 'Monaco',
      code: 'MC',
      dialCode: '+377',
      flag: '🇲🇨',
    ),
    Country(
      nameEn: 'Mongolia',
      nameId: 'Mongolia',
      code: 'MN',
      dialCode: '+976',
      flag: '🇲🇳',
    ),
    Country(
      nameEn: 'Montenegro',
      nameId: 'Montenegro',
      code: 'ME',
      dialCode: '+382',
      flag: '🇲🇪',
    ),
    Country(
      nameEn: 'Montserrat',
      nameId: 'Montserrat',
      code: 'MS',
      dialCode: '+1664',
      flag: '🇲🇸',
    ),
    Country(
      nameEn: 'Morocco',
      nameId: 'Maroko',
      code: 'MA',
      dialCode: '+212',
      flag: '🇲🇦',
    ),
    Country(
      nameEn: 'Mozambique',
      nameId: 'Mozambique',
      code: 'MZ',
      dialCode: '+258',
      flag: '🇲🇿',
    ),
    Country(
      nameEn: 'Myanmar',
      nameId: 'Myanmar',
      code: 'MM',
      dialCode: '+95',
      flag: '🇲🇲',
    ),
    Country(
      nameEn: 'Namibia',
      nameId: 'Namibia',
      code: 'NA',
      dialCode: '+264',
      flag: '🇳🇦',
    ),
    Country(
      nameEn: 'Nauru',
      nameId: 'Nauru',
      code: 'NR',
      dialCode: '+674',
      flag: '🇳🇷',
    ),
    Country(
      nameEn: 'Nepal',
      nameId: 'Nepal',
      code: 'NP',
      dialCode: '+977',
      flag: '🇳🇵',
    ),
    Country(
      nameEn: 'Netherlands',
      nameId: 'Belanda',
      code: 'NL',
      dialCode: '+31',
      flag: '🇳🇱',
    ),
    Country(
      nameEn: 'Netherlands Antilles',
      nameId: 'Netherlands Antilles',
      code: 'AN',
      dialCode: '+599',
      flag: '🇦🇳',
    ),
    Country(
      nameEn: 'New Caledonia',
      nameId: 'New Caledonia',
      code: 'NC',
      dialCode: '+687',
      flag: '🇳🇨',
    ),
    Country(
      nameEn: 'New Zealand',
      nameId: 'Selandia Baru',
      code: 'NZ',
      dialCode: '+64',
      flag: '🇳🇿',
    ),
    Country(
      nameEn: 'Nicaragua',
      nameId: 'Nicaragua',
      code: 'NI',
      dialCode: '+505',
      flag: '🇳🇮',
    ),
    Country(
      nameEn: 'Niger',
      nameId: 'Niger',
      code: 'NE',
      dialCode: '+227',
      flag: '🇳🇪',
    ),
    Country(
      nameEn: 'Nigeria',
      nameId: 'Nigeria',
      code: 'NG',
      dialCode: '+234',
      flag: '🇳🇬',
    ),
    Country(
      nameEn: 'Niue',
      nameId: 'Niue',
      code: 'NU',
      dialCode: '+683',
      flag: '🇳🇺',
    ),
    Country(
      nameEn: 'Norfolk Island',
      nameId: 'Norfolk Island',
      code: 'NF',
      dialCode: '+672',
      flag: '🇳🇫',
    ),
    Country(
      nameEn: 'Northern Mariana Islands',
      nameId: 'Northern Mariana Islands',
      code: 'MP',
      dialCode: '+1670',
      flag: '🇲🇵',
    ),
    Country(
      nameEn: 'Norway',
      nameId: 'Norway',
      code: 'NO',
      dialCode: '+47',
      flag: '🇳🇴',
    ),
    Country(
      nameEn: 'Oman',
      nameId: 'Oman',
      code: 'OM',
      dialCode: '+968',
      flag: '🇴🇲',
    ),
    Country(
      nameEn: 'Pakistan',
      nameId: 'Pakistan',
      code: 'PK',
      dialCode: '+92',
      flag: '🇵🇰',
    ),
    Country(
      nameEn: 'Palau',
      nameId: 'Palau',
      code: 'PW',
      dialCode: '+680',
      flag: '🇵🇼',
    ),
    Country(
      nameEn: 'Palestinian Territory, Occupied',
      nameId: 'Palestinian Territory, Occupied',
      code: 'PS',
      dialCode: '+970',
      flag: '🇵🇸',
    ),
    Country(
      nameEn: 'Panama',
      nameId: 'Panama',
      code: 'PA',
      dialCode: '+507',
      flag: '🇵🇦',
    ),
    Country(
      nameEn: 'Papua New Guinea',
      nameId: 'Papua New Guinea',
      code: 'PG',
      dialCode: '+675',
      flag: '🇵🇬',
    ),
    Country(
      nameEn: 'Paraguay',
      nameId: 'Paraguay',
      code: 'PY',
      dialCode: '+595',
      flag: '🇵🇾',
    ),
    Country(
      nameEn: 'Peru',
      nameId: 'Peru',
      code: 'PE',
      dialCode: '+51',
      flag: '🇵🇪',
    ),
    Country(
      nameEn: 'Philippines',
      nameId: 'Filipina',
      code: 'PH',
      dialCode: '+63',
      flag: '🇵🇭',
    ),
    Country(
      nameEn: 'Pitcairn',
      nameId: 'Pitcairn',
      code: 'PN',
      dialCode: '+872',
      flag: '🇵🇳',
    ),
    Country(
      nameEn: 'Poland',
      nameId: 'Poland',
      code: 'PL',
      dialCode: '+48',
      flag: '🇵🇱',
    ),
    Country(
      nameEn: 'Portugal',
      nameId: 'Portugal',
      code: 'PT',
      dialCode: '+351',
      flag: '🇵🇹',
    ),
    Country(
      nameEn: 'Puerto Rico',
      nameId: 'Puerto Rico',
      code: 'PR',
      dialCode: '+1939',
      flag: '🇵🇷',
    ),
    Country(
      nameEn: 'Qatar',
      nameId: 'Qatar',
      code: 'QA',
      dialCode: '+974',
      flag: '🇶🇦',
    ),
    Country(
      nameEn: 'Romania',
      nameId: 'Romania',
      code: 'RO',
      dialCode: '+40',
      flag: '🇷🇴',
    ),
    Country(
      nameEn: 'Russia',
      nameId: 'Russia',
      code: 'RU',
      dialCode: '+7',
      flag: '🇷🇺',
    ),
    Country(
      nameEn: 'Rwanda',
      nameId: 'Rwanda',
      code: 'RW',
      dialCode: '+250',
      flag: '🇷🇼',
    ),
    Country(
      nameEn: 'Reunion',
      nameId: 'Reunion',
      code: 'RE',
      dialCode: '+262',
      flag: '🇷🇪',
    ),
    Country(
      nameEn: 'Saint Barthelemy',
      nameId: 'Saint Barthelemy',
      code: 'BL',
      dialCode: '+590',
      flag: '🇧🇱',
    ),
    Country(
      nameEn: 'Saint Helena, Ascension and Tristan Da Cunha',
      nameId: 'Saint Helena, Ascension and Tristan Da Cunha',
      code: 'SH',
      dialCode: '+290',
      flag: '🇸🇭',
    ),
    Country(
      nameEn: 'Saint Kitts and Nevis',
      nameId: 'Saint Kitts and Nevis',
      code: 'KN',
      dialCode: '+1869',
      flag: '🇰🇳',
    ),
    Country(
      nameEn: 'Saint Lucia',
      nameId: 'Saint Lucia',
      code: 'LC',
      dialCode: '+1758',
      flag: '🇱🇨',
    ),
    Country(
      nameEn: 'Saint Martin',
      nameId: 'Saint Martin',
      code: 'MF',
      dialCode: '+590',
      flag: '🇲🇫',
    ),
    Country(
      nameEn: 'Saint Pierre and Miquelon',
      nameId: 'Saint Pierre and Miquelon',
      code: 'PM',
      dialCode: '+508',
      flag: '🇵🇲',
    ),
    Country(
      nameEn: 'Saint Vincent and the Grenadines',
      nameId: 'Saint Vincent and the Grenadines',
      code: 'VC',
      dialCode: '+1784',
      flag: '🇻🇨',
    ),
    Country(
      nameEn: 'Samoa',
      nameId: 'Samoa',
      code: 'WS',
      dialCode: '+685',
      flag: '🇼🇸',
    ),
    Country(
      nameEn: 'San Marino',
      nameId: 'San Marino',
      code: 'SM',
      dialCode: '+378',
      flag: '🇸🇲',
    ),
    Country(
      nameEn: 'Sao Tome and Principe',
      nameId: 'Sao Tome and Principe',
      code: 'ST',
      dialCode: '+239',
      flag: '🇸🇹',
    ),
    Country(
      nameEn: 'Saudi Arabia',
      nameId: 'Arab Saudi',
      code: 'SA',
      dialCode: '+966',
      flag: '🇸🇦',
    ),
    Country(
      nameEn: 'Senegal',
      nameId: 'Senegal',
      code: 'SN',
      dialCode: '+221',
      flag: '🇸🇳',
    ),
    Country(
      nameEn: 'Serbia',
      nameId: 'Serbia',
      code: 'RS',
      dialCode: '+381',
      flag: '🇷🇸',
    ),
    Country(
      nameEn: 'Seychelles',
      nameId: 'Seychelles',
      code: 'SC',
      dialCode: '+248',
      flag: '🇸🇨',
    ),
    Country(
      nameEn: 'Sierra Leone',
      nameId: 'Sierra Leone',
      code: 'SL',
      dialCode: '+232',
      flag: '🇸🇱',
    ),
    Country(
      nameEn: 'Singapore',
      nameId: 'Singapura',
      code: 'SG',
      dialCode: '+65',
      flag: '🇸🇬',
    ),
    Country(
      nameEn: 'Slovakia',
      nameId: 'Slovakia',
      code: 'SK',
      dialCode: '+421',
      flag: '🇸🇰',
    ),
    Country(
      nameEn: 'Slovenia',
      nameId: 'Slovenia',
      code: 'SI',
      dialCode: '+386',
      flag: '🇸🇮',
    ),
    Country(
      nameEn: 'Solomon Islands',
      nameId: 'Solomon Islands',
      code: 'SB',
      dialCode: '+677',
      flag: '🇸🇧',
    ),
    Country(
      nameEn: 'Somalia',
      nameId: 'Somalia',
      code: 'SO',
      dialCode: '+252',
      flag: '🇸🇴',
    ),
    Country(
      nameEn: 'South Africa',
      nameId: 'South Africa',
      code: 'ZA',
      dialCode: '+27',
      flag: '🇿🇦',
    ),
    Country(
      nameEn: 'South Sudan',
      nameId: 'South Sudan',
      code: 'SS',
      dialCode: '+211',
      flag: '🇸🇸',
    ),
    Country(
      nameEn: 'South Georgia and the South Sandwich Islands',
      nameId: 'South Georgia and the South Sandwich Islands',
      code: 'GS',
      dialCode: '+500',
      flag: '🇬🇸',
    ),
    Country(
      nameEn: 'Spain',
      nameId: 'Spanyol',
      code: 'ES',
      dialCode: '+34',
      flag: '🇪🇸',
    ),
    Country(
      nameEn: 'Sri Lanka',
      nameId: 'Sri Lanka',
      code: 'LK',
      dialCode: '+94',
      flag: '🇱🇰',
    ),
    Country(
      nameEn: 'Sudan',
      nameId: 'Sudan',
      code: 'SD',
      dialCode: '+249',
      flag: '🇸🇩',
    ),
    Country(
      nameEn: 'Suriname',
      nameId: 'Suriname',
      code: 'SR',
      dialCode: '+597',
      flag: '🇸🇷',
    ),
    Country(
      nameEn: 'Svalbard and Jan Mayen',
      nameId: 'Svalbard and Jan Mayen',
      code: 'SJ',
      dialCode: '+47',
      flag: '🇸🇯',
    ),
    Country(
      nameEn: 'Swaziland',
      nameId: 'Swaziland',
      code: 'SZ',
      dialCode: '+268',
      flag: '🇸🇿',
    ),
    Country(
      nameEn: 'Sweden',
      nameId: 'Sweden',
      code: 'SE',
      dialCode: '+46',
      flag: '🇸🇪',
    ),
    Country(
      nameEn: 'Switzerland',
      nameId: 'Swiss',
      code: 'CH',
      dialCode: '+41',
      flag: '🇨🇭',
    ),
    Country(
      nameEn: 'Syrian Arab Republic',
      nameId: 'Syrian Arab Republic',
      code: 'SY',
      dialCode: '+963',
      flag: '🇸🇾',
    ),
    Country(
      nameEn: 'Taiwan',
      nameId: 'Taiwan',
      code: 'TW',
      dialCode: '+886',
      flag: '🇹🇼',
    ),
    Country(
      nameEn: 'Tajikistan',
      nameId: 'Tajikistan',
      code: 'TJ',
      dialCode: '+992',
      flag: '🇹🇯',
    ),
    Country(
      nameEn: 'Tanzania, United Republic of Tanzania',
      nameId: 'Tanzania, United Republic of Tanzania',
      code: 'TZ',
      dialCode: '+255',
      flag: '🇹🇿',
    ),
    Country(
      nameEn: 'Thailand',
      nameId: 'Thailand',
      code: 'TH',
      dialCode: '+66',
      flag: '🇹🇭',
    ),
    Country(
      nameEn: 'Timor-Leste',
      nameId: 'Timor-Leste',
      code: 'TL',
      dialCode: '+670',
      flag: '🇹🇱',
    ),
    Country(
      nameEn: 'Togo',
      nameId: 'Togo',
      code: 'TG',
      dialCode: '+228',
      flag: '🇹🇬',
    ),
    Country(
      nameEn: 'Tokelau',
      nameId: 'Tokelau',
      code: 'TK',
      dialCode: '+690',
      flag: '🇹🇰',
    ),
    Country(
      nameEn: 'Tonga',
      nameId: 'Tonga',
      code: 'TO',
      dialCode: '+676',
      flag: '🇹🇴',
    ),
    Country(
      nameEn: 'Trinidad and Tobago',
      nameId: 'Trinidad and Tobago',
      code: 'TT',
      dialCode: '+1868',
      flag: '🇹🇹',
    ),
    Country(
      nameEn: 'Tunisia',
      nameId: 'Tunisia',
      code: 'TN',
      dialCode: '+216',
      flag: '🇹🇳',
    ),
    Country(
      nameEn: 'Turkey',
      nameId: 'Turki',
      code: 'TR',
      dialCode: '+90',
      flag: '🇹🇷',
    ),
    Country(
      nameEn: 'Turkmenistan',
      nameId: 'Turkmenistan',
      code: 'TM',
      dialCode: '+993',
      flag: '🇹🇲',
    ),
    Country(
      nameEn: 'Turks and Caicos Islands',
      nameId: 'Turks and Caicos Islands',
      code: 'TC',
      dialCode: '+1649',
      flag: '🇹🇨',
    ),
    Country(
      nameEn: 'Tuvalu',
      nameId: 'Tuvalu',
      code: 'TV',
      dialCode: '+688',
      flag: '🇹🇻',
    ),
    Country(
      nameEn: 'Uganda',
      nameId: 'Uganda',
      code: 'UG',
      dialCode: '+256',
      flag: '🇺🇬',
    ),
    Country(
      nameEn: 'Ukraine',
      nameId: 'Ukraine',
      code: 'UA',
      dialCode: '+380',
      flag: '🇺🇦',
    ),
    Country(
      nameEn: 'United Arab Emirates',
      nameId: 'United Arab Emirates',
      code: 'AE',
      dialCode: '+971',
      flag: '🇦🇪',
    ),
    Country(
      nameEn: 'United Kingdom',
      nameId: 'Inggris',
      code: 'GB',
      dialCode: '+44',
      flag: '🇬🇧',
    ),
    Country(
      nameEn: 'United States',
      nameId: 'Amerika Serikat',
      code: 'US',
      dialCode: '+1',
      flag: '🇺🇸',
    ),
    Country(
      nameEn: 'Uruguay',
      nameId: 'Uruguay',
      code: 'UY',
      dialCode: '+598',
      flag: '🇺🇾',
    ),
    Country(
      nameEn: 'Uzbekistan',
      nameId: 'Uzbekistan',
      code: 'UZ',
      dialCode: '+998',
      flag: '🇺🇿',
    ),
    Country(
      nameEn: 'Vanuatu',
      nameId: 'Vanuatu',
      code: 'VU',
      dialCode: '+678',
      flag: '🇻🇺',
    ),
    Country(
      nameEn: 'Venezuela, Bolivarian Republic of Venezuela',
      nameId: 'Venezuela, Bolivarian Republic of Venezuela',
      code: 'VE',
      dialCode: '+58',
      flag: '🇻🇪',
    ),
    Country(
      nameEn: 'Vietnam',
      nameId: 'Vietnam',
      code: 'VN',
      dialCode: '+84',
      flag: '🇻🇳',
    ),
    Country(
      nameEn: 'Virgin Islands, British',
      nameId: 'Virgin Islands, British',
      code: 'VG',
      dialCode: '+1284',
      flag: '🇻🇬',
    ),
    Country(
      nameEn: 'Virgin Islands, U.S.',
      nameId: 'Virgin Islands, U.S.',
      code: 'VI',
      dialCode: '+1340',
      flag: '🇻🇮',
    ),
    Country(
      nameEn: 'Wallis and Futuna',
      nameId: 'Wallis and Futuna',
      code: 'WF',
      dialCode: '+681',
      flag: '🇼🇫',
    ),
    Country(
      nameEn: 'Yemen',
      nameId: 'Yemen',
      code: 'YE',
      dialCode: '+967',
      flag: '🇾🇪',
    ),
    Country(
      nameEn: 'Zambia',
      nameId: 'Zambia',
      code: 'ZM',
      dialCode: '+260',
      flag: '🇿🇲',
    ),
    Country(
      nameEn: 'Zimbabwe',
      nameId: 'Zimbabwe',
      code: 'ZW',
      dialCode: '+263',
      flag: '🇿🇼',
    ),
  ];
}
